//login do usuario
# POST  http://localhost:3333/auth/login
POST https://max-chat-oudo.onrender.com/auth/login
Content-Type: application/json

{
    "name": "max",
    "password": "123456"
}
###

//registro do usuario
POST  http://localhost:3333/auth/register
Content-Type: application/json

{
    "name": "teste8",
    "password": "123456"
}